# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = 3D_Reconstruction
DESTDIR = ../x64/Debug
CONFIG += debug console
LIBS += -L"." \
    -lopencv_world346d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .

RC_FILE+= 3D_Reconstruction.rc